import { Permissions } from "@/auth/permissions.js";

/**
 * Centralized Action Configuration for all DroneIQ / AeroNexus Fly Page Operations.
 * 
 * Defines metadata, severity, warnings, and permission gates for every discrete
 * operational command that can mutate flight, drone, camera, gimbal, or mission state.
 */
export const FLY_ACTION_CONFIG = {
  ARM: {
    action: "ARM",
    title: "Confirm Arm",
    message: (droneId) => `Are you sure you want to arm ${droneId || "the aircraft"}?`,
    warning: "Arming will activate the drone motors. Ensure all personnel and obstacles are clear of propeller sweep areas.",
    confirmLabel: "Confirm Arm",
    cancelLabel: "Cancel",
    severity: "warning",
    requiredPermission: Permissions.EXECUTE_FLIGHT_COMMANDS,
  },
  DISARM: {
    action: "DISARM",
    title: "Confirm Disarm",
    message: (droneId) => `Are you sure you want to disarm ${droneId || "the aircraft"}?`,
    warning: "Disarming will immediately stop the drone motors.",
    confirmLabel: "Confirm Disarm",
    cancelLabel: "Cancel",
    severity: "danger",
    requiredPermission: Permissions.EXECUTE_FLIGHT_COMMANDS,
  },
  TAKEOFF: {
    action: "TAKEOFF",
    title: "Confirm Takeoff",
    message: (droneId) => `Are you sure you want to initiate takeoff for ${droneId || "the aircraft"}?`,
    warning: "Ensure the takeoff zone and surrounding airspace are clear of obstacles and personnel before proceeding.",
    targetAltitude: "10 m",
    confirmLabel: "Confirm Takeoff",
    cancelLabel: "Cancel",
    severity: "warning",
    requiredPermission: Permissions.EXECUTE_FLIGHT_COMMANDS,
  },
  LAND: {
    action: "LAND",
    title: "Confirm Land",
    message: (droneId) => `Are you sure you want to land ${droneId || "the aircraft"}?`,
    warning: "The drone will begin its landing sequence at current coordinates.",
    confirmLabel: "Confirm Land",
    cancelLabel: "Cancel",
    severity: "danger",
    requiredPermission: Permissions.EXECUTE_FLIGHT_COMMANDS,
  },
  RTL: {
    action: "RTL",
    title: "Confirm RTL",
    message: (droneId) => `Are you sure you want ${droneId || "the aircraft"} to return to its launch/home location?`,
    warning: "The aircraft will ascend to RTL altitude and automatically navigate back to Home position.",
    confirmLabel: "Confirm RTL",
    cancelLabel: "Cancel",
    severity: "warning",
    requiredPermission: Permissions.EXECUTE_FLIGHT_COMMANDS,
  },
  OVERRIDE_RTL: {
    action: "OVERRIDE_RTL",
    title: "Confirm Override RTL",
    message: "This will override the current flight behavior and initiate RTL.",
    warning: "Priority emergency command: Supersedes routine pilot control and immediately routes the drone to home.",
    confirmLabel: "Confirm Override RTL",
    cancelLabel: "Cancel",
    severity: "warning",
    requiredPermission: Permissions.OVERRIDE_FLIGHT_COMMANDS,
  },
  EMERGENCY_LAND: {
    action: "EMERGENCY_LAND",
    title: "Confirm Emergency Land",
    message: "Emergency landing will immediately initiate the drone's landing procedure. Are you sure you want to continue?",
    warning: "HIGH-SEVERITY EMERGENCY: Immediate descent will initiate at current coordinates. Verify surface clearance.",
    confirmLabel: "Confirm Emergency Land",
    cancelLabel: "Cancel",
    severity: "danger",
    requiredPermission: Permissions.OVERRIDE_FLIGHT_COMMANDS,
  },
  FORCE_DISARM: {
    action: "FORCE_DISARM",
    title: "Confirm Force Disarm",
    message: (droneId) => `Force disarm is a high-risk emergency action. Are you sure you want to force disarm ${droneId || "the aircraft"}?`,
    warning: "CRITICAL WARNING: Immediate motor cutoff will execute. The aircraft will drop from current altitude without control.",
    confirmLabel: "Confirm Force Disarm",
    cancelLabel: "Cancel",
    severity: "danger",
    requiredPermission: Permissions.OVERRIDE_FLIGHT_COMMANDS,
  },
  ABORT_MISSION: {
    action: "ABORT_MISSION",
    title: "Confirm Abort Mission",
    message: "Are you sure you want to abort the current mission?",
    warning: "This action terminates the autonomous waypoint sequence immediately and commands the aircraft to hover/hold position.",
    confirmLabel: "Confirm Abort Mission",
    cancelLabel: "Cancel",
    severity: "danger",
    requiredPermission: Permissions.OVERRIDE_FLIGHT_COMMANDS,
  },
  FLIGHT_MODE_CHANGE: {
    action: "FLIGHT_MODE_CHANGE",
    title: "Confirm Flight Mode Change",
    message: (fromMode, toMode) => `Change flight mode from ${fromMode} to ${toMode}?`,
    warning: (toMode) => `Ensure aircraft is trimmed and ready for ${toMode} mode dynamics.`,
    confirmLabel: "Confirm Change",
    cancelLabel: "Cancel",
    severity: "warning",
    requiredPermission: Permissions.EXECUTE_FLIGHT_COMMANDS,
  },
  GIMBAL_CENTER: {
    action: "GIMBAL_CENTER",
    title: "Confirm Gimbal Center",
    message: "Align gimbal forward with drone heading (Pitch 0°, Roll 0°, Yaw = Drone Heading)?",
    warning: "Gimbal will immediately rotate to neutral forward boresight orientation.",
    confirmLabel: "Confirm Gimbal Center",
    cancelLabel: "Cancel",
    severity: "info",
    requiredPermission: Permissions.EXECUTE_FLIGHT_COMMANDS,
  },
  GIMBAL_LEVEL_ROLL: {
    action: "GIMBAL_LEVEL_ROLL",
    title: "Confirm Level Roll",
    message: "Reset gimbal roll angle to 0.0° level horizon?",
    warning: "Gimbal roll will return to neutral level alignment.",
    confirmLabel: "Confirm Level Roll",
    cancelLabel: "Cancel",
    severity: "info",
    requiredPermission: Permissions.EXECUTE_FLIGHT_COMMANDS,
  },
  START_MISSION: {
    action: "START_MISSION",
    title: "Confirm Start Mission",
    message: "Initiate autonomous waypoint mission execution?",
    warning: "Aircraft will switch to AUTO mode and proceed to Waypoint 1.",
    confirmLabel: "Confirm Start Mission",
    cancelLabel: "Cancel",
    severity: "warning",
    requiredPermission: Permissions.EXECUTE_FLIGHT_COMMANDS,
  },
  PAUSE_MISSION: {
    action: "PAUSE_MISSION",
    title: "Confirm Pause Mission",
    message: "Pause autonomous mission and loiter at current position?",
    warning: "Aircraft will hold current position in LOITER mode until resumed.",
    confirmLabel: "Confirm Pause Mission",
    cancelLabel: "Cancel",
    severity: "warning",
    requiredPermission: Permissions.EXECUTE_FLIGHT_COMMANDS,
  },
  RESUME_MISSION: {
    action: "RESUME_MISSION",
    title: "Confirm Resume Mission",
    message: "Resume autonomous mission navigation along designated waypoint path?",
    warning: "Aircraft will switch back to AUTO mode and resume waypoint sequence.",
    confirmLabel: "Confirm Resume Mission",
    cancelLabel: "Cancel",
    severity: "warning",
    requiredPermission: Permissions.EXECUTE_FLIGHT_COMMANDS,
  },
};
