/**
 * AeroNexus GCS Canonical Permissions
 * Centralized definition of all system permissions.
 */

export const Permissions = Object.freeze({
  SYSTEM_CONFIG: "SYSTEM_CONFIG",
  MANAGE_USERS: "MANAGE_USERS",
  INVITE_USERS: "INVITE_USERS",
  MANAGE_DRONES: "MANAGE_DRONES",
  VIEW_DRONES: "VIEW_DRONES",
  CREATE_MISSIONS: "CREATE_MISSIONS",
  EDIT_MISSIONS: "EDIT_MISSIONS",
  DELETE_MISSIONS: "DELETE_MISSIONS",
  EXECUTE_FLIGHT_COMMANDS: "EXECUTE_FLIGHT_COMMANDS",
  OVERRIDE_FLIGHT_COMMANDS: "OVERRIDE_FLIGHT_COMMANDS",
  PUBLISH_TELEMETRY: "PUBLISH_TELEMETRY",
  TRIAGE_INCIDENTS: "TRIAGE_INCIDENTS",
  EXPORT_EVIDENCE: "EXPORT_EVIDENCE",
  VIEW_MISSIONS: "VIEW_MISSIONS",
  VIEW_INCIDENTS: "VIEW_INCIDENTS",
  VIEW_LOGS: "VIEW_LOGS",
});

export default Permissions;
